### ISSUE TITLE
Make sure that the property `interfaceOnly` is exposed

### ISSUE THREAD

**Issue by ricardozanini** [quarkiverse/quarkus-openapi-generator#174]
See: https://openapi-generator.tech/docs/generators/jaxrs-spec/

We already use this generator underneath. The property `interfaceOnly` can be exposed by the plugin. The trick here is also to update the templates to ensure that the property is considered.

Request: https://github.com/quarkiverse/quarkus-openapi-generator/issues/128#issuecomment-1310557441

**Comment by KiMurray** [comment]
Im a little confused. 
> We already use this generator underneath.
My understanding was that this extension uses the Java client generator, has something changed? / Can this extension also generate server stubs? 
Cheers

**Comment by ricardozanini** [comment]
We use the Java Client Generator from the OpenAPI Generator library. Theoretically we can generate server stubs too, but it's out of scope. 

The idea behind this issue is to implement a similar behavior in the client side, so instead of generating something like this:

```java
@Produces(MediaType.APPLICATION_JSON)
@Path("/petstore")
public class PetResource {

    @RestClient
    @Inject
    PetApi petApi;
}
```

We do this:

```java
@Produces(MediaType.APPLICATION_JSON)
@Path("/petstore")
public class PetResource {

    @RestClient
    @Inject
    Response petApi;
}
```

@KiMurray that's what you're looking for, right?

**Comment by hbelmiro** [comment]
Sorry @KiMurray. It seems to be the same as @ricardozanini is saying in his previous comment.
Am I missing something?

**Comment by KiMurray** [comment]
@ricardozanini, yes! your updated comment is exactly what we need. Had me a little confused for a moment there. 😄

**Comment by hbelmiro** [comment]
@ricardozanini this issue's requirement is not very clear.
My understanding from @KiMurray's [original comment](https://github.com/quarkiverse/quarkus-openapi-generator/issues/128#issuecomment-1310557441) is 2 requirements:
1) Generate server code
This could be achieved by exposing `interfaceOnly`, but this is out of the scope of this extension and we won't implement it.

2) Return `Response` instead of a model
Is this related with `interfaceOnly`? If yes, I think we shouldn't use `interfaceOnly` to enable/disable this, since it may confuse users and actually wouldn't describe the "return `Response`" feature.

**Comment by ricardozanini** [comment]
`interfaceOnly` is just a name. As soon as we start working on the enhancement, we can develop a new name for this property.

The problem is that this property name can be used for a server side or client code gen, hence the confusion. But no, we won't generate server-side code. The requirement is to generate the Model with the `Response` interface instead of the actual data model.
