### ISSUE TITLE
Specify a different root path for files

### ISSUE THREAD

**Issue by gwydionmv** [quarkiverse/quarkus-openapi-generator#176]
I'd like to add a new functionality to the generators to allow changing the root path from "src/main/openapi" to a custom one, and also being able to filter which files inside that directory must be used. I've been doing some tests and it could be done with just 2 new optional properties and a couple of new lines in OpenApiGeneratorCodeGenBase.

I found that OpenApiGeneratorStreamCodeGen could potentially achieve something similar but it needs to create a new library to define the new provider.

What do you think? Thanks!

**Comment by hbelmiro** [comment]
Go ahead @gwydionmv. I can help with the review.
I think you can do it in OpenApiGeneratorCodeGenBase.

Regarding a filter, we already have something similar implemented but not yet released.
https://github.com/quarkiverse/quarkus-openapi-generator#ignoring-openapi-specification-files
If you need this now we can release a new version. Just let me know.

**Comment by gwydionmv** [comment]
Nice @hbelmiro , thanks a lot!

About that filter using an _ignore_ property, I considered using it but for our use case it's going to be much better having a "positive filter" than a negative one. I also think that it helps towards maintainability specifying which files to use than which not to use.

And if not, better having both functionalities and let everyone use the one they prefer 😃

**Comment by ricardozanini** [comment]
@gwydionmv, why change the default directory from `src/main/openapi` to any other? I think it's fine for filtering, but let's try merging it with the ignore filtering feature. What I mean is that both should be ubiquitous in UX. For example:

```properties
quarkus.open-api.generator.codegen.include=<expression>
quarkus.open-api.generator.codegen.exclude=<expression>
```

Also, let's design so that `OpenApiGeneratorCodeGenBase` would be associated with this feature and not implemented directly in that class.

Lastly, you can implement your own filtering/source via [`OpenAPISpecInputProvider`](https://github.com/quarkiverse/quarkus-openapi-generator/tree/main/integration-tests/generation-tests) implementation.

I'd rather not change the default path via property.

**Comment by gwydionmv** [comment]
@ricardozanini I'm working on a project in which we have several products (microservices) that comunicate with each other. We want to use git submodules to share the openapi formats across all of them, and we just need some of the client classes in each of the microservices. That's the reason for both features: changing the base directory to be able to load the files from the submodule, and selecting which files are to be analysed depending on the product (as I said before, it's more maintainable to select the ones we want than the ones we don't).

I already aligned the properties to be include/exclude as you said before, I'll open the PR and we can continue the discussion over there. Thanks!
