### ISSUE TITLE
Authentication Bearer not matching paths

### ISSUE THREAD

**Issue by arnodtza** [quarkiverse/quarkus-openapi-generator#304]
We generate the RestClient interface from a predefined yaml definition with Security Schema set to something similar as:
securitySchemes:
   user-auth:
     type: http
    description: Security schema using bearer tokens.
     scheme: bearer
     bearerFormat: JWT
The paths for the restricted endpoit in the yaml is:
/api/v1/user
We added the following in the properties file:
quarkus.rest-client."openapi_user_yaml".url=https://my.server.com/restservice
quarkus.openapi-generator."openapi_user_yaml".auth.user-auth.bearer-token=kfdjaslkfdjghlkdsfjhglksdfjhglkjdshfglak

With this configuration the Authorization header is not added to the outgoing message. After debugging we found that the CompositeAuthenticationProvider try to watch the path as:
restservice/api/v1/user to /api/v1/user

We are using Quarkus version 2.16.3 and quarkus-openapi-generator version 1.3.1

Could you please advise if we miss some configuration in the properties file. We dont want to at restservice path to the yaml definition as this can change and should not be included.

Thanks

**Comment by hbelmiro** [comment]
### How to reproduce

Use https://github.com/quarkiverse/quarkus-openapi-generator/tree/main/integration-tests/security.

1. Add the following line to [`application.properties`](https://github.com/quarkiverse/quarkus-openapi-generator/blob/a0728c9cd6d8665776666bac49ac216c5649d1c4/integration-tests/security/src/main/resources/application.properties):

```properties
quarkus.openapi-generator.codegen.spec.open_weather_yaml.url=https://api.openweathermap.org/data/2.5
```

2. Remove [this line](https://github.com/quarkiverse/quarkus-openapi-generator/blob/a0728c9cd6d8665776666bac49ac216c5649d1c4/integration-tests/security/src/main/openapi/open%20weather.yaml#L16) from `open weather.yaml`.

3. See the test fail

The test fails because the generated `CompositeAuthenticationProvider` doesn't include the full path

```java
    @PostConstruct
    public void init() {

        ApiKeyAuthenticationProvider apiKeyQueryProvider0 = new ApiKeyAuthenticationProvider("open_weather_yaml", sanitizeAuthName("app_id"), ApiKeyIn.query, "appid", generatorConfig);
        this.addAuthenticationProvider(apiKeyQueryProvider0);
        apiKeyQueryProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/weather") // <------ HERE
            .withId("currentWeatherData")
            .withMethod("GET")
            .build());
    }
```

When the OpenAPI document contains the URL, the generated `CompositeAuthenticationProvider` looks like:

```java
    @PostConstruct
    public void init() {

        ApiKeyAuthenticationProvider apiKeyQueryProvider0 = new ApiKeyAuthenticationProvider("open_weather_yaml", sanitizeAuthName("app_id"), ApiKeyIn.query, "appid", generatorConfig);
        this.addAuthenticationProvider(apiKeyQueryProvider0);
        apiKeyQueryProvider0.addOperation(OperationAuthInfo.builder()
            .withPath("/data/2.5/weather") // <----- IT SHOULD GENERATE LIKE THIS
            .withId("currentWeatherData")
            .withMethod("GET")
            .build());
    }
```

**Comment by arnodtza** [comment]
Thanks for the replay.
Yes that was also what we discovered but our requirement is that we do not want to specify the full path in the  OpenAPI document. Only the part that is specific to the API `/api/v1/user`

The path specified in the properties file should not be used when comparing the paths in the `CompositeAuthenticationProvider`.

Because the sever `https://my.server.com` and the first part of the path `/restservice` can change; therefore we don't want to re-release the micro-service but only want to change the property in K8s environment.

Is there any possibility to accomplish this?

Thanks

**Comment by ricardozanini** [comment]
@hbelmiro the `CompositeAuthenticationProvider` should override the URL provided in the YAML definition if found a `.url` property in the system.

**Comment by michalsomora** [comment]
Hi @ricardozanini , whats the plan to fix this limitation? We cant change the url in application.properties without breaking the authorization since the default CompositeAuthenticationProvider expects perfect match of the api path called vs api path defined in swagger. I think this issue is related to #394.

**Comment by ricardozanini** [comment]
@leonardobazico mind sharing a reproducer?
