### ISSUE TITLE
“You need to add io.quarkus:quarkus-rest-client-reactive-jackson to your dependencies.” even though it’s present

### ISSUE THREAD

**Issue by patr1kt0th** [quarkiverse/quarkus-openapi-generator#499]
Hi guys. I was about to update our project to the latest Quarkus version (3.4.1) and got a strange error when trying to compile our `conversion-connector` (the only one using `quarkus-openapi-generator` version `2.2.10`). We use the `reactive` versions of the dependencies:

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-reactive-jackson</artifactId>
    </dependency>
```

and after I try to compile (or run) the application using `./mvnw clean compile`, I get:

```
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.4.1:generate-code (default) on project conversion-connector: Quarkus code generation phase has failed: InvocationTargetException: You need to add io.quarkus:quarkus-rest-client-reactive-jackson to your dependencies. -> [Help 1]
```

By using the `-e` switch, the cause is shown:

```
Caused by: io.quarkus.bootstrap.prebuild.CodeGenException: You need to add io.quarkus:quarkus-rest-client-reactive-jackson to your dependencies.
    at io.quarkiverse.openapi.generator.deployment.codegen.OpenApiGeneratorCodeGenBase.trigger (OpenApiGeneratorCodeGenBase.java:103)
```

And after checking deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java's history and trying the same with the current code base from `main`, the `throw` moved to line 106.

Using the `classic` versions of the dependencies:

```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-multipart</artifactId>
    </dependency>
```

I'm able to compile and run the application without any issues.

@hbelmiro , @ricardozanini , do you have an idea what's going on here? I can check in more details tomorrow, but maybe you know it right away?

**Comment by hbelmiro** [comment]
No idea @patr1kt0th 🙁
I’d have to take a further look.

**Comment by willemsendennis** [comment]
Same here with quarkus 3.4.1 on gradle.

**Comment by chberger** [comment]
@hbelmiro : I've analyzed this issue.

With Quarkus ``3.4.1``, the Quarkus team has changed the identifier for the ``REST_CLIENT_REACTIVE_JACKSON`` capability. That's the related commit: https://github.com/quarkusio/quarkus/commit/29181b3ef439a5bd082810252130e93dfef55839

However, the latest version of ``quarkus-openapi-generator`` expects this capability via the id ``io.quarkus.rest.client.reactive.jackson`` as it has been compiled with Quarkus < ``3.4.1``. Now Quarkus provides this capability with the following id ``io.quarkus.rest.client.reactive.json.jackson``. Obviously, this cannot work anymore.

I guess we just need to recompile the ``quarkus-openapi-generator`` with the latest version of Quarkus ``3.4.1`` and it should work again. However, this change is not backward compatible because the resulting version would not work with Quarkus apps < ``3.4.1``. 

**Solution idea:** we could determine the Quarkus version at build time and request the correct capability id accordingly. By doing so, the extension would be compatible with Quarkus < ``3.4.1`` and >= ``3.4.1``.

Shall I implement a PR?

**Comment by hbelmiro** [comment]
Many thanks for investigating @chberger ❤️ 
Please go ahead with the PR.

**Comment by chberger** [comment]
Here we go: https://github.com/quarkiverse/quarkus-openapi-generator/pull/500

This PR is still marked as draft since I don't have automated tests. Maybe the community can test that version and verify that everything works as expected. @hbelmiro wdyt?

**Comment by patr1kt0th** [comment]
@chberger I can definitely give it a try on our codebase where we use Quarkus version **3.3.1** on `main` and **3.4.1** on `dev`.
