### ISSUE TITLE
Support unexpected values in Enums

### ISSUE THREAD

**Issue by brice-laurencin** [quarkiverse/quarkus-openapi-generator#692]
If the server evolves and adds (or, God forbid, deletes) entries in an enum, the client will likely fail hard.

It'd be interesting to add a default `UNEXPECTED` value in all the generated enum, this one being the default value when parsing fails.

I can try to cook a PR for this, if you think that's a sensible idea.

**Comment by ricardozanini** [comment]
Feel free to experiment, @brice-laurencin. I'm curious about this use case since it's somewhat common. In my experience, usually the server would change the API to a new version e.g. `/v2/petstore`, then new clients can use this new endpoint and interface.

Changing the main version to not be compatible smells and it's an anti-pattern. So I'm not sure how much resources we should spend on this.
