### ISSUE TITLE
@ApplicationScoped required for mocking api and missing 

### ISSUE THREAD

**Issue by miguelchico** [quarkiverse/quarkus-openapi-generator#86]
Hello

Following the official Quarkus guide (https://quarkus.io/blog/mocking/#using-injectmock) I found out I need to use the @ApplicationScoped annotation in the interface defining the api and that annotation is missing in the generated code here.

Is there any way of adding it? Is it possible mocking in any other way?

Thanks

**Comment by ricardozanini** [comment]
Hi @miguelchico! Currently, you can't. We can add it in here, though: https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/deployment/src/main/resources/templates/api.qute#L40.

Can you send a PR and run some tests to evaluate it? 

As a workaround, I think you can try overwriting the interface and adding your annotation there.

**Comment by miguelchico** [comment]
@ricardozanini I sent a super small PR, please check it when you have the time.

Thank you

**Comment by Shohou** [comment]
@ricardozanini, @miguelchico is this annotation still needed with current quarkus?
https://quarkus.io/guides/rest-client-reactive#mocking-with-injectmock - doesn't require it...
I have opposite situation. I implement generated Api interface with my mock class and because of `ApplicationScoped` annotation quarkus thinks it's server-side rest methods and application exposes them for calling from outside.
